export const USER_ORDERS_PER_PAGE = 5;
export const USER_RETURNS_PER_PAGE = 5;
export const USER_CANCELLATIONS_PER_PAGE = 5;
export const USER_REVIEWS_PER_PAGE = 10;

export const SEARCH_PRODUCTS_PER_PAGE = 10;
export const PRODUCTS_REVIEWS_PER_PAGE = 3;
export const MATCHING_PRODUCTS_PER_PAGE = 12;
export const PRODUCTS_QUESTIONS_PER_PAGE = 5;

export const STORE_PRODUCTS_PER_PAGE = 15;

export const QUESTIONS_PER_BUCKET_COUNT = 200;
export const RATING_AND_REVIEWS_PER_BUCKET_COUNT = 200;
